// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "nav": {
    "packages": "Packages",
    "clients": "Clients",
    "start": "Start",
    "theme": {
      "light": "Light",
      "dark": "Dark",
      "system": "System"
    },
    "language": {
      "english": "English",
      "italian": "Italian"
    }
  },
  "hero": {
    "title": "Brand. Build. Boom.",
    "subtitle": "AI-driven websites live in days, not months.",
    "cta": "Start now!"
  },
  "pricing": {
    "title": "Packages",
    "fast": {
      "name": "Fast & Simple",
      "tagline": "Let the world know you exist.",
      "price": "€40 / month",
      "feature1": "Branding",
      "feature2": "One-page custom design",
      "feature3": "2 business-day delivery",
      "feature4": "Copy in EN+IT",
      "feature5": "SEO meta",
      "feature6": "1 revision",
      "feature7": "Managed hosting (10k visits)"
    },
    "custom": {
      "name": "Custom Made",
      "tagline": "Custom web apps. No limits. Just results.",
      "price": "from €5,000 + €40 / month",
      "feature1": "SaaS platforms",
      "feature2": "Web portals & dashboards",
      "feature3": "Auth & admin",
      "feature4": "API integrations",
      "feature5": "Scalable infra"
    },
    "addons": "Add-ons",
    "addonsDescription": "Enhance your package with additional services"
  },
  "portfolio": {
    "title": "Clients",
    "subtitle": "See what we've built for businesses like yours"
  },
  "footer": {
    "brandDescription": "AI-driven digital agency empowering small businesses with professional online presence.",
    "quickLinks": "Quick Links",
    "followUs": "Follow Us",
    "copyright": "© 2025 WhiteBoar · VAT No. 1234567890"
  },
  "meta": {
    "title": "WhiteBoar - AI-Driven Digital Agency",
    "description": "Transform your business with AI-driven websites and branding. Professional online presence in days, not months."
  },
  "onboarding": {
    "title": "Get Started with WhiteBoar",
    "description": "Choose your path to a powerful online presence. We'll guide you through every step.",
    "step": "Step",
    "of": "of",
    "next": "Next",
    "progressLabel": "Step {step} of {total}",
    "stepCompleted": "Step {step} completed",
    "stepCurrent": "Current step {step}",
    "stepUpcoming": "Upcoming step {step}",
    "previous": "Previous",
    "step1": {
      "title": "Fast & Simple",
      "description": "Perfect for small businesses who need a professional online presence quickly. Get a custom one-page website with branding in just 2 business days.",
      "button": "Choose Fast & Simple"
    },
    "step2": {
      "title": "Custom Solution",
      "description": "Need something more complex? Let's discuss your custom web application, SaaS platform, or advanced business requirements.",
      "button": "Start Custom Project"
    },
    "help_text": "Not sure which option is right for you?",
    "contact_support": "Contact our team for guidance",
    "meta": {
      "title": "Get Started - WhiteBoar",
      "description": "Begin your journey with WhiteBoar. Choose between Fast & Simple or Custom solutions for your business needs."
    },
    "welcome": {
      "title": "Welcome to WhiteBoar",
      "subtitle": "Let's create your perfect website in just 12 simple steps. Our AI-driven process ensures a professional result tailored to your business.",
      "features": {
        "fast": {
          "title": "Lightning Fast",
          "description": "Complete setup in minutes, live website in 2 business days."
        },
        "secure": {
          "title": "Secure & Reliable",
          "description": "SSL encryption, managed hosting, and automatic backups included."
        },
        "smart": {
          "title": "AI-Powered",
          "description": "Smart recommendations and automated optimizations for your business."
        }
      },
      "process": {
        "title": "How It Works",
        "steps": {
          "1": {
            "title": "Business Details",
            "description": "Tell us about your business and goals."
          },
          "2": {
            "title": "Design Preferences",
            "description": "Choose your style and visual preferences."
          },
          "3": {
            "title": "Content & Assets",
            "description": "Upload your logo and business content."
          },
          "4": {
            "title": "Review & Launch",
            "description": "Final review and your website goes live."
          }
        }
      },
      "requirements": {
        "title": "What You'll Need",
        "business": {
          "title": "Business Information",
          "name": "Business name and description",
          "email": "Contact email address",
          "address": "Business address (optional)",
          "phone": "Phone number (optional)"
        },
        "assets": {
          "title": "Optional Assets",
          "logo": "Business logo (PNG, JPG, or SVG)",
          "photos": "Business photos or product images",
          "examples": "Examples of websites you like",
          "content": "Existing content or copy"
        }
      },
      "actions": {
        "start": "Start Your Website",
        "continue": "Continue Where You Left Off",
        "startOver": "Start Over",
        "restart": "Restart"
      },
      "disclaimer": "Takes approximately 10-15 minutes. Your progress is automatically saved."
    },
    "saving": "Saving...",
    "saved": "Saved",
    "loading": "Loading...",
    "complete": "Complete",
    "sessionExpired": {
      "title": "Session Expired",
      "description": "Your session has expired for security reasons. You can recover your progress or start over.",
      "recover": "Recover Session",
      "startOver": "Start Over"
    },
    "emailVerification": {
      "title": "Verify Your Email",
      "description": "We've sent a 6-digit verification code to <email>{emailValue}</email>. Please enter it below to continue.",
      "enterCode": "Enter verification code",
      "verifying": "Verifying code...",
      "codeComplete": "Code complete",
      "codeSent": "Verification code sent successfully",
      "verify": "Verify Code",
      "didntReceive": "Didn't receive the code?",
      "sending": "Sending...",
      "resendIn": "Resend in {seconds}s",
      "resendCode": "Resend Code",
      "resendError": "Failed to resend code. Please try again.",
      "clear": "Clear",
      "changeEmail": "Change Email",
      "checkSpam": "Check your spam/junk folder if you don't see the email.",
      "pasteSupported": "You can paste the code from your clipboard.",
      "digitLabel": "Verification code digit {position}"
    },
    "steps": {
      "validationError": "Please correct the errors above before proceeding.",
      "nextStepError": "Failed to proceed to next step. Please try again.",
      "submissionError": "Failed to submit your onboarding. Please try again.",
      "complete": "Complete Onboarding",
      "finish": "Finish",
      "back": "Back to Welcome",
      "1": {
        "title": "Welcome",
        "description": "Let's get started with your business information",
        "welcome": "Welcome to WhiteBoar",
        "subtitle": "Let's create your perfect website in just a few simple steps.",
        "stats": {
          "steps": "Simple Steps",
          "minutes": "Minutes Total",
          "price": "Per Month"
        },
        "contactInfo": {
          "title": "Your Contact Information",
          "required": "Required",
          "firstName": {
            "label": "First Name",
            "placeholder": "Enter your first name",
            "hint": "Your first name as you'd like it to appear"
          },
          "lastName": {
            "label": "Last Name",
            "placeholder": "Enter your last name",
            "hint": "Your last name for professional communication"
          },
          "email": {
            "label": "Email Address",
            "placeholder": "Enter your email address",
            "hint": "We'll use this to send you updates and the final website"
          }
        },
        "nextSteps": {
          "title": "What's Next",
          "step1": "Business details and goals",
          "step2": "Design preferences and style",
          "step3": "Content and final review"
        },
        "privacy": {
          "notice": "Your information is secure and will only be used to create your website.",
          "policy": "Privacy Policy",
          "terms": "Terms of Service"
        }
      },
      "2": {
        "title": "Email Verification",
        "description": "Verify your email address to continue",
        "invalidCode": "Invalid verification code. Please check and try again.",
        "verificationFailed": "Email verification failed. Please try again."
      },
      "3": {
        "title": "Business Details",
        "description": "Tell us about your business",
        "businessInfo": {
          "title": "Business Information",
          "required": "Required",
          "name": {
            "label": "Business Name",
            "placeholder": "Enter your business name",
            "hint": "The official name of your business"
          },
          "industry": {
            "label": "Industry",
            "placeholder": "Select your industry",
            "hint": "What type of business do you operate?"
          },
          "vat": {
            "label": "VAT Number",
            "placeholder": "IT12345678901",
            "hint": "Italian VAT number (optional)"
          }
        },
        "contactInfo": {
          "title": "Contact Information",
          "required": "Required",
          "email": {
            "label": "Business Email",
            "placeholder": "business@company.com",
            "hint": "Your main business email address"
          },
          "phone": {
            "label": "Business Phone",
            "hint": "Your main business phone number"
          },
          "website": {
            "label": "Current Website",
            "placeholder": "https://your-website.com",
            "hint": "Your current website URL (if you have one)"
          }
        },
        "address": {
          "title": "Business Address",
          "required": "Required",
          "street": {
            "label": "Street Address",
            "placeholder": "Enter your business address",
            "hint": "Start typing your address for suggestions"
          },
          "city": {
            "label": "City",
            "placeholder": "Enter city"
          },
          "postalCode": {
            "label": "Postal Code",
            "placeholder": "58000"
          },
          "city": {
            "label": "City",
            "placeholder": "Enter city"
          },
          "postalCode": {
            "label": "Postal Code",
            "placeholder": "58000"
          },
          "region": {
            "label": "Province/Region",
            "placeholder": "Enter province or region"
          },
          "country": {
            "label": "Country",
            "placeholder": "Enter country"
          }
        },
        "dataUsage": {
          "notice": "This information will be used to create your business website and may appear publicly."
        }
      },
      "4": {
        "title": "Brand Definition",
        "description": "Define your unique value proposition and competitive positioning",
        "offering": {
          "title": "What You Offer",
          "required": "Required",
          "description": {
            "label": "Business Description",
            "placeholder": "Describe what your business offers in one sentence that would appeal to a new customer",
            "hint": "Keep it clear and compelling - think about what makes customers choose you"
          }
        },
        "audience": {
          "title": "Target Audience",
          "optional": "Optional",
          "description": {
            "label": "Who are your ideal customers?",
            "placeholder": "Describe your typical customers (age, interests, needs, etc.)",
            "hint": "Understanding your audience helps us create content that resonates"
          }
        },
        "uniqueness": {
          "title": "What Makes You Unique",
          "required": "Required",
          "value": {
            "label": "Your Unique Value",
            "placeholder": "What sets you apart from competitors? What do you do better or differently?",
            "hint": "Think about your strengths, special services, or unique approach"
          },
          "goals": {
            "label": "Business Goals",
            "placeholder": "What are your main business objectives for the next year?",
            "hint": "Examples: increase sales, expand market reach, improve customer service"
          }
        },
        "competitors": {
          "title": "Competitor Analysis",
          "optional": "Optional",
          "description": "Help us understand your market by sharing competitor websites",
          "urls": {
            "label": "Competitor Websites",
            "placeholder": "https://competitor-website.com",
            "addButton": "Add Competitor",
            "hint": "Share up to 5 competitor websites to help us differentiate your brand"
          },
          "analysis": {
            "label": "Competitive Analysis",
            "placeholder": "What do you like/dislike about your competitors? What gaps do you see in the market?",
            "hint": "Help us understand how to position your business uniquely"
          }
        },
        "keywords": {
          "title": "Brand Keywords",
          "description": "What words best describe your brand personality?",
          "input": {
            "label": "Brand Keywords",
            "placeholder": "Enter keywords that describe your brand (e.g., professional, innovative, reliable)",
            "hint": "Choose 3-5 words that best represent your brand personality and values"
          },
          "examples": {
            "professional": "Professional, trustworthy, established",
            "innovative": "Innovative, cutting-edge, modern",
            "reliable": "Reliable, dependable, consistent",
            "creative": "Creative, unique, artistic"
          }
        }
      },
      "5": {
        "title": "Target Audience",
        "description": "Who are your ideal customers?",
        "intro": {
          "title": "Customer Profiling",
          "description": "Help us understand your ideal customers by adjusting these sliders to match their typical characteristics."
        },
        "profile": {
          "title": "Customer Profile",
          "required": "Required",
          "budget": {
            "left": "Budget-Conscious",
            "right": "Premium-Focused",
            "description": "How price-sensitive are your customers?",
            "examples": {
              "left": {
                "price": "Looks for best deals and discounts",
                "discount": "Compares prices across competitors",
                "value": "Values affordability over luxury"
              },
              "right": {
                "quality": "Willing to pay more for quality",
                "premium": "Values premium features and service",
                "exclusive": "Seeks exclusive or luxury options"
              }
            }
          },
          "style": {
            "left": "Traditional",
            "right": "Modern",
            "description": "What design aesthetic do they prefer?",
            "examples": {
              "left": {
                "classic": "Prefers classic, timeless designs",
                "proven": "Trusts established, proven approaches",
                "conservative": "Conservative, risk-averse choices"
              },
              "right": {
                "innovative": "Attracted to innovative solutions",
                "trendy": "Follows latest trends and technology",
                "cutting": "Early adopters of cutting-edge products"
              }
            }
          },
          "motivation": {
            "left": "Practical",
            "right": "Aspirational",
            "description": "What drives their purchasing decisions?",
            "examples": {
              "left": {
                "functional": "Focuses on practical benefits",
                "efficient": "Values efficiency and functionality",
                "practical": "Makes decisions based on utility"
              },
              "right": {
                "memorable": "Seeks memorable experiences",
                "emotional": "Driven by emotional connection",
                "inspiring": "Values inspiration and aspiration"
              }
            }
          },
          "decision": {
            "left": "Quick Decider",
            "right": "Careful Researcher",
            "description": "How do they make purchasing decisions?",
            "examples": {
              "left": {
                "impulse": "Responsive to immediate needs",
                "quick": "Makes quick, intuitive decisions",
                "instinct": "Trusts gut feelings and first impressions"
              },
              "right": {
                "research": "Extensively researches before buying",
                "compare": "Carefully compares options and features",
                "deliberate": "Takes time to make thoughtful decisions"
              }
            }
          },
          "loyalty": {
            "left": "Price Switcher",
            "right": "Brand Loyal",
            "description": "How loyal are they to brands?",
            "examples": {
              "left": {
                "deals": "Switches based on price or deals",
                "compare": "Always compares options before buying",
                "switch": "Open to trying new brands and services"
              },
              "right": {
                "relationship": "Values long-term relationships",
                "trust": "Sticks with trusted brands and providers",
                "consistent": "Prefers consistency and reliability"
              }
            }
          }
        },
        "insights": {
          "title": "Targeting Insights",
          "description": "Based on your selections, we'll tailor your website's messaging and design to appeal to your ideal customers.",
          "targeting": {
            "title": "Website Messaging",
            "messaging": "Content tone and language will match customer preferences",
            "pricing": "Pricing presentation will align with budget expectations",
            "features": "Feature highlights will emphasize what matters most"
          },
          "optimization": {
            "title": "Design & Layout",
            "layout": "Page layout will suit decision-making style",
            "content": "Visual hierarchy will guide customer journey",
            "calls": "Call-to-action placement will maximize conversions"
          }
        },
        "tips": {
          "honest": "Be honest about your actual customers, not who you wish they were",
          "typical": "Think about your most typical customers, not outliers",
          "adjust": "You can adjust these settings later as your business evolves"
        }
      },
      "6": {
        "title": "Customer Needs",
        "description": "Understanding what your customers really need",
        "intro": {
          "title": "Understanding Customer Challenges",
          "description": "Help us understand what problems your customers face and how your business solves them. This insight will shape your website's messaging and positioning."
        },
        "problems": {
          "title": "Customer Problems & Pain Points",
          "required": "Required",
          "examples": {
            "title": "Common customer challenges:",
            "visibility": "Hard to find reliable service providers online",
            "credibility": "Difficulty assessing business credibility and quality",
            "competition": "Too many options, unclear differentiation",
            "communication": "Poor communication or unclear pricing"
          },
          "input": {
            "label": "What main problems do your customers face?",
            "placeholder": "Describe the specific challenges your customers experience before they find your business...",
            "hint": "Focus on the problems you solve - this helps us craft compelling website messaging"
          }
        },
        "solutions": {
          "title": "Your Solutions & Benefits",
          "required": "Required",
          "examples": {
            "title": "How your business solves problems:",
            "professional": "Professional website establishes instant credibility",
            "seo": "SEO-optimized content helps customers find you easily",
            "mobile": "Mobile-friendly design serves customers anywhere",
            "social": "Social proof and testimonials build trust"
          },
          "input": {
            "label": "How does your business solve these problems?",
            "placeholder": "Explain the specific ways your products or services address customer challenges...",
            "hint": "Be specific about the benefits and outcomes customers get from choosing you"
          }
        },
        "delight": {
          "title": "Customer Delight Moments",
          "optional": "Optional",
          "examples": {
            "title": "Ways to exceed expectations:",
            "surprise": "Unexpected bonuses or added value",
            "personal": "Personalized service and attention to detail",
            "exceed": "Going above and beyond standard service",
            "memorable": "Creating memorable experiences customers share"
          },
          "input": {
            "label": "How do you exceed customer expectations?",
            "placeholder": "Describe the special touches or extra value that make customers love working with you...",
            "hint": "These unique advantages will become key selling points on your website"
          }
        },
        "insights": {
          "title": "Customer Journey Insights",
          "awareness": {
            "title": "Awareness Stage",
            "description": "How customers discover they need your solution"
          },
          "consideration": {
            "title": "Consideration Stage",
            "description": "How customers evaluate and compare options"
          },
          "decision": {
            "title": "Decision Stage",
            "description": "What makes customers choose you over competitors"
          }
        },
        "tips": {
          "title": "Tips for better responses:",
          "specific": "Be specific and concrete",
          "customer": "Think from customer perspective",
          "emotional": "Include emotional benefits"
        }
      },
      "7": {
        "title": "Visual Inspiration",
        "description": "Show us websites and designs you admire",
        "intro": {
          "title": "Design Inspiration & References",
          "description": "Share websites you find visually appealing or functionally impressive. This helps us understand your aesthetic preferences and design direction."
        },
        "inspirations": {
          "title": "Website Inspirations",
          "optional": "Optional",
          "guidelines": {
            "title": "What to look for in inspiration websites:",
            "layout": "Clean, organized layout and structure",
            "colors": "Color schemes that appeal to you",
            "typography": "Text styles and readability",
            "navigation": "Easy-to-use navigation and menus",
            "images": "High-quality photos and graphics",
            "overall": "Overall feel and user experience"
          },
          "urls": {
            "label": "Inspiration Website URLs",
            "placeholder": "https://example-website.com",
            "addButton": "Add Website",
            "hint": "Add up to 10 websites that inspire you. Include competitors, similar businesses, or any sites you find well-designed."
          }
        },
        "categories": {
          "title": "Quick Categories",
          "description": "Click to add sample websites from different industries",
          "restaurant": "Restaurant & Food",
          "retail": "Retail & E-commerce",
          "professional": "Professional Services",
          "creative": "Creative & Portfolio"
        },
        "preferences": {
          "title": "Visual Preferences",
          "optional": "Optional",
          "examples": {
            "title": "Describe your preferred style:",
            "clean": "Clean and minimalist with lots of white space",
            "bold": "Bold and vibrant with strong visual impact",
            "professional": "Professional and trustworthy appearance",
            "creative": "Creative and unique with artistic elements"
          },
          "input": {
            "label": "Describe your visual preferences",
            "placeholder": "Tell us about the look and feel you want for your website - colors, layout style, mood, etc...",
            "hint": "This helps us understand your design direction beyond just inspiration websites"
          }
        },
        "analysis": {
          "title": "Design Analysis Process",
          "layout": {
            "title": "Layout Analysis",
            "description": "We'll analyze structure and organization patterns"
          },
          "content": {
            "title": "Content Strategy",
            "description": "We'll examine how content is presented and organized"
          },
          "interaction": {
            "title": "User Experience",
            "description": "We'll study navigation and user interaction patterns"
          }
        },
        "tips": {
          "title": "Tips for better inspiration:",
          "diverse": "Include diverse examples",
          "specific": "Be specific about what you like",
          "relevant": "Choose sites relevant to your industry"
        }
      },
      "8": {
        "title": "Design Style",
        "description": "Choose the visual style that best represents your brand",
        "intro": {
          "title": "Choose Your Design Style",
          "description": "Select the design approach that best reflects your brand personality and appeals to your target audience. This will guide the overall visual direction of your website."
        },
        "selection": {
          "title": "Design Style Selection",
          "required": "Required"
        },
        "characteristics": {
          "title": "Design Style Impact",
          "visual": {
            "title": "Visual Elements",
            "layout": "Page structure and organization",
            "typography": "Font choices and text hierarchy",
            "spacing": "White space and element positioning",
            "elements": "Buttons, forms, and interactive components"
          },
          "impact": {
            "title": "Business Impact",
            "perception": "How customers perceive your professionalism",
            "audience": "Appeal to your target demographic",
            "conversion": "Influence on user actions and decisions",
            "branding": "Consistency with your brand identity"
          }
        },
        "recommendations": {
          "title": "Industry Style Recommendations",
          "restaurant": {
            "title": "Restaurant & Food",
            "style": "Warm & Friendly or Bold & Creative"
          },
          "professional": {
            "title": "Professional Services",
            "style": "Corporate Professional or Classic Elegant"
          },
          "creative": {
            "title": "Creative Industries",
            "style": "Bold & Creative or Modern Minimal"
          },
          "retail": {
            "title": "Retail & E-commerce",
            "style": "Modern Minimal or Warm & Friendly"
          },
          "health": {
            "title": "Health & Wellness",
            "style": "Classic Elegant or Warm & Friendly"
          },
          "luxury": {
            "title": "Luxury & Premium",
            "style": "Luxury Premium or Classic Elegant"
          }
        },
        "tips": {
          "title": "Choose a style that:",
          "authentic": "Feels authentic to your brand",
          "audience": "Appeals to your target audience",
          "flexible": "Works across different devices"
        }
      },
      "9": {
        "title": "Image Style",
        "description": "Choose the visual style for your website's imagery",
        "intro": {
          "title": "Choose Your Image Style",
          "description": "Select the type of imagery that best represents your brand and connects with your audience. This choice will guide all visual content throughout your website."
        },
        "selection": {
          "title": "Image Style Selection",
          "required": "Required"
        },
        "impact": {
          "title": "Visual Impact & Considerations",
          "psychology": {
            "title": "Psychological Impact",
            "trust": "Professional images build credibility and trust",
            "emotion": "Lifestyle photos create emotional connections",
            "attention": "Creative visuals capture and hold attention",
            "memory": "Unique imagery makes your brand memorable"
          },
          "technical": {
            "title": "Technical Benefits",
            "loading": "Optimized images ensure fast loading times",
            "scalability": "Vector graphics scale perfectly on all devices",
            "responsive": "Professional photos work across all screen sizes",
            "accessibility": "Clear imagery improves accessibility for all users"
          }
        },
        "combinations": {
          "title": "Industry Style Combinations",
          "business": {
            "title": "Business & Professional",
            "professional": "Professional Photography + Clean Minimalist",
            "clean": "Clean composition for trust and credibility",
            "mixed": "Mixed Creative for dynamic presentations"
          },
          "creative": {
            "title": "Creative & Artistic",
            "handDrawn": "Hand-Drawn Style for unique personality",
            "lifestyle": "Lifestyle Photography for authentic feel",
            "modern": "Modern Illustrations for contemporary appeal"
          },
          "hospitality": {
            "title": "Hospitality & Food",
            "lifestyle": "Lifestyle Photography for appetizing visuals",
            "professional": "Professional Photography for quality impression",
            "warm": "Warm tones to create inviting atmosphere"
          },
          "tech": {
            "title": "Technology & SaaS",
            "modern": "Modern Illustrations for innovation",
            "minimalist": "Minimalist Clean for focus and clarity",
            "mixed": "Mixed Creative for engaging presentations"
          }
        },
        "strategy": {
          "title": "Content Strategy Integration",
          "description": "Your chosen image style will influence how we source, create, and optimize all visual content for your website.",
          "consistency": "Consistent visual language across all pages",
          "quality": "High-quality imagery that reflects your brand values",
          "relevance": "Images that support and enhance your message"
        },
        "tips": {
          "title": "Choose images that:",
          "brand": "Align with your brand personality",
          "audience": "Resonate with your target audience",
          "quality": "Maintain high quality standards"
        }
      },
      "10": {
        "title": "Color Palette",
        "description": "Choose colors that represent your brand perfectly",
        "intro": {
          "title": "Color Palette Selection",
          "description": "Colors play a crucial role in how customers perceive your brand. Choose a palette that reflects your business personality and appeals to your target audience."
        },
        "selection": {
          "title": "Choose Your Color Palette",
          "required": "Required"
        },
        "psychology": {
          "title": "Color Psychology",
          "emotional": {
            "title": "Emotional Impact",
            "trust": "Blue builds trust and professionalism",
            "energy": "Orange and red create energy and urgency",
            "calm": "Green promotes calm and natural feelings",
            "luxury": "Purple conveys luxury and sophistication"
          },
          "business": {
            "title": "Business Benefits",
            "conversion": "Right colors can increase conversion rates by up to 80%",
            "branding": "Consistent colors improve brand recognition by 80%",
            "accessibility": "Proper contrast ensures accessibility for all users",
            "recognition": "Signature colors make your brand memorable"
          }
        },
        "trends": {
          "title": "Industry Color Trends",
          "finance": {
            "title": "Finance & Banking",
            "description": "Blues, greens, and grays for trust and stability"
          },
          "health": {
            "title": "Health & Wellness",
            "description": "Greens, blues, and teals for healing and growth"
          },
          "food": {
            "title": "Food & Restaurant",
            "description": "Warm oranges, reds, and yellows to stimulate appetite"
          },
          "tech": {
            "title": "Technology",
            "description": "Purples, blues, and dark tones for innovation"
          },
          "fashion": {
            "title": "Fashion & Beauty",
            "description": "Bold pinks, blacks, and purples for style"
          },
          "education": {
            "title": "Education",
            "description": "Blues, greens, and oranges for learning and growth"
          }
        },
        "accessibility": {
          "title": "Accessibility & Standards",
          "description": "We ensure all color combinations meet accessibility standards for optimal user experience.",
          "contrast": "Minimum 4.5:1 contrast ratio for text readability",
          "colorBlind": "Color schemes work for color-blind users",
          "consistency": "Consistent color usage across all elements"
        },
        "tips": {
          "title": "Choose colors that:",
          "emotion": "Match your brand emotion",
          "industry": "Fit your industry",
          "accessible": "Are accessible to all"
        }
      },
      "11": {
        "title": "Website Structure",
        "description": "Define your website's purpose and organize its content effectively",
        "intro": {
          "title": "Plan Your Website Structure",
          "description": "Define your primary goals and choose the sections that will help you achieve them. A well-structured website guides visitors smoothly toward your desired actions."
        },
        "goal": {
          "title": "Primary Website Goal",
          "required": "Required",
          "selection": {
            "label": "What is your main goal for this website?",
            "placeholder": "Select your primary objective",
            "hint": "This will influence which sections we recommend and how we structure your content"
          }
        },
        "sections": {
          "title": "Website Sections",
          "required": "Required",
          "essential": "Essential",
          "recommended": {
            "title": "Recommended sections for",
            "badge": "Recommended"
          }
        },
        "offerings": {
          "title": "Products & Services",
          "optional": "Optional",
          "examples": {
            "title": "Examples of what you might offer:",
            "consulting": "Business consulting services",
            "design": "Web design and branding",
            "development": "Software development",
            "photography": "Professional photography",
            "marketing": "Digital marketing services",
            "training": "Training and workshops"
          },
          "list": {
            "label": "Your Products/Services",
            "placeholder": "Enter a product or service",
            "addButton": "Add Item",
            "hint": "List your main products or services - this helps us create targeted content for each offering"
          }
        },
        "insights": {
          "title": "Structure & User Experience",
          "navigation": {
            "title": "Navigation Design",
            "clear": "Clear, intuitive menu structure",
            "logical": "Logical information hierarchy",
            "mobile": "Mobile-friendly navigation patterns"
          },
          "conversion": {
            "title": "Conversion Optimization",
            "cta": "Strategic call-to-action placement",
            "trust": "Trust signals and social proof positioning",
            "contact": "Easy access to contact information"
          }
        },
        "tips": {
          "title": "Structure tips:",
          "essential": "Include essential sections",
          "goal": "Align with your main goal",
          "simple": "Keep navigation simple"
        }
      },
      "12": {
        "title": "Business Assets",
        "description": "Upload your business logo and photos to personalize your website",
        "intro": {
          "title": "Business Assets",
          "description": "Upload your business logo and photos to personalize your website and build trust with customers."
        },
        "logo": {
          "title": "Business Logo",
          "optional": "Optional",
          "guidelines": "Upload a high-quality logo in PNG, JPG, or SVG format. Maximum file size: 2MB.",
          "upload": {
            "label": "Upload Logo",
            "hint": "Drag and drop your logo here or click to browse files"
          },
          "requirements": {
            "title": "Logo Requirements",
            "format": "PNG, JPG, or SVG format",
            "size": "Maximum 2MB file size",
            "resolution": "Minimum 300px width",
            "background": "Transparent background preferred",
            "colors": "High contrast for visibility",
            "quality": "Professional appearance"
          }
        },
        "photos": {
          "title": "Business Photos",
          "optional": "Optional",
          "benefits": {
            "title": "Why business photos matter:",
            "trust": "Build trust and credibility",
            "personal": "Create personal connection",
            "professional": "Showcase professionalism"
          },
          "upload": {
            "label": "Upload Photos",
            "hint": "Upload up to 30 photos, 10MB each. Show your business, team, or services."
          }
        },
        "categories": {
          "title": "Photo Categories",
          "exterior": {
            "title": "Exterior & Location",
            "storefront": "Storefront and building exterior",
            "signage": "Business signage and branding",
            "entrance": "Entrance and accessibility"
          },
          "interior": {
            "title": "Interior & Workspace",
            "workspace": "Working environment and facilities",
            "products": "Products or service areas",
            "atmosphere": "Ambiance and customer areas"
          },
          "team": {
            "title": "Team & People",
            "owner": "Business owner or manager",
            "staff": "Team members and employees",
            "action": "People in action, serving customers"
          },
          "services": {
            "title": "Services & Process",
            "process": "Services being performed",
            "results": "Before and after examples",
            "tools": "Equipment and tools used"
          }
        },
        "summary": {
          "title": "Upload Summary",
          "logo": "Logo",
          "photos": "Photos",
          "uploaded": "Uploaded",
          "none": "None uploaded",
          "photoCount": "{count} photos"
        },
        "quality": {
          "title": "Photo Quality Tips",
          "lighting": {
            "title": "Good Lighting",
            "description": "Natural light or well-lit environments work best"
          },
          "composition": {
            "title": "Clear Composition",
            "description": "Focus on the subject, avoid cluttered backgrounds"
          },
          "authenticity": {
            "title": "Authentic Moments",
            "description": "Genuine interactions and real business activities"
          }
        },
        "tips": {
          "title": "Remember:",
          "quality": "Quality over quantity",
          "authentic": "Authentic moments",
          "variety": "Show variety"
        }
      }
    },
    "thankYou": {
      "title": "Perfect! We have everything we need.",
      "message": "Our team will analyze your information and prepare a preview tailored to attract your ideal customers and differentiate you from competitors.",
      "timeline": {
        "title": "Preview Ready",
        "description": "In 5 business days"
      },
      "notification": {
        "title": "Email Notification",
        "description": "You'll receive an email when it's ready"
      },
      "payment": {
        "title": "Payment",
        "description": "Only after you approve the preview"
      },
      "nextSteps": {
        "title": "What happens next?",
        "step1": "Our team analyzes your responses and creates a custom website preview",
        "step2": "You'll receive an email with your preview link within 5 business days",
        "step3": "Review the preview and only pay if you're completely satisfied"
      },
      "backHome": "Back to Homepage"
    }
  },
  "forms": {
    "required": "This field is required",
    "invalid": "Please enter a valid value",
    "tooShort": "This field is too short",
    "tooLong": "This field is too long",
    "characterMinimum": "Must be at least {count} characters",
    "characterMaximum": "Must be no more than {count} characters",
    "showPassword": "Show password",
    "hidePassword": "Hide password",
    "dynamicList": {
      "add": "Add Item",
      "remove": "Remove",
      "empty": "No items added",
      "placeholder": "Enter item and press Enter",
      "duplicate": "This item has already been added"
    },
    "email": {
      "invalid": "Please enter a valid email address",
      "checking": "Checking email...",
      "valid": "Email is valid",
      "taken": "This email is already in use"
    },
    "dropdown": {
      "placeholder": "Select an option",
      "search": "Search...",
      "noResults": "No results found",
      "loading": "Loading...",
      "required": "This field is required"
    },
    "phone": {
      "invalid": "Please enter a valid phone number",
      "valid": "Phone number is valid",
      "selectCountry": "Select country",
      "searchCountries": "Search countries...",
      "required": "This field is required"
    },
    "address": {
      "searching": "Searching...",
      "noResults": "No addresses found",
      "selectFromList": "Please select an address from the list",
      "googleMapsRequired": "Google Maps API is required for address autocomplete",
      "required": "This field is required"
    },
    "colorPalette": {
      "required": "Please select a color palette",
      "noSelection": "No palette selected",
      "preview": "Preview",
      "copyColor": "Copy color code",
      "copied": "Copied!",
      "uncategorized": "Uncategorized",
      "all": "All",
      "selectedPalette": "Selected Palette",
      "colors": "Colors",
      "usage": "Usage",
      "noPalettes": "No color palettes available"
    },
    "slider": {
      "reset": "Reset to center",
      "required": "This field is required"
    },
    "imageGrid": {
      "premium": "Premium",
      "all": "All",
      "uncategorized": "Uncategorized",
      "required": "Required",
      "selectedCount": "{count} of {max} selected",
      "noOptions": "No options available",
      "imageLoadError": "Failed to load image",
      "preview": "Preview"
    },
    "fileUpload": {
      "dragAndDrop": "Drag and drop files here, or click to select",
      "maxSize": "Max {maxSize}MB per file, {maxFiles} files max",
      "selectFiles": "Select Files"
    }
  },
  "common": {
    "loading": "Loading...",
    "saving": "Saving...",
    "saved": "Saved",
    "error": "Error",
    "success": "Success",
    "required": "Required",
    "optional": "Optional",
    "close": "Close",
    "cancel": "Cancel",
    "confirm": "Confirm",
    "continue": "Continue",
    "back": "Back",
    "next": "Next",
    "submit": "Submit",
    "save": "Save",
    "edit": "Edit",
    "delete": "Delete",
    "add": "Add",
    "remove": "Remove"
  },
  "customSoftware": {
    "meta": {
      "title": "Custom Software Development - WhiteBoar",
      "description": "Professional custom web and mobile application development. SaaS platforms, dashboards, API integrations, and more."
    },
    "hero": {
      "title": "Custom Software Development",
      "subtitle": "From concept to launch, we build custom solutions that scale with your business",
      "description": "Whether you need a SaaS platform, mobile app, or complex web application, our team delivers professional software tailored to your exact requirements."
    },
    "services": {
      "title": "What We Build",
      "webApps": "Web Applications",
      "webAppsDesc": "Full-stack custom web applications with modern frameworks",
      "mobileApps": "Mobile Apps",
      "mobileAppsDesc": "Native iOS and Android applications",
      "saas": "SaaS Platforms",
      "saasDesc": "Multi-tenant platforms with subscription management",
      "dashboards": "Custom Dashboards",
      "dashboardsDesc": "Data visualization and business intelligence tools",
      "api": "API Integrations",
      "apiDesc": "Connect your systems and automate workflows",
      "ecommerce": "E-commerce Solutions",
      "ecommerceDesc": "Custom online stores and payment processing"
    },
    "form": {
      "title": "Tell Us About Your Project",
      "subtitle": "Share your vision and we'll help bring it to life",
      "nameLabel": "Name",
      "namePlaceholder": "Your name",
      "emailLabel": "Email",
      "emailPlaceholder": "your@email.com",
      "phoneLabel": "Phone",
      "phonePlaceholder": "+39 123 456 7890",
      "descriptionLabel": "Describe what you would like us to build",
      "descriptionPlaceholder": "Tell us about your project, goals, and any specific requirements...",
      "submitButton": "Send",
      "submitting": "Sending...",
      "success": {
        "title": "Thank you!",
        "message": "We will be in touch within 2 business days."
      },
      "errors": {
        "nameRequired": "Name is required",
        "nameTooShort": "Name must be at least 2 characters",
        "emailRequired": "Email is required",
        "emailInvalid": "Please enter a valid email address",
        "phoneRequired": "Phone is required",
        "phoneInvalid": "Please enter a valid phone number",
        "descriptionRequired": "Project description is required",
        "descriptionTooShort": "Please provide more details (at least 20 characters)",
        "submitFailed": "Failed to send your request. Please try again."
      }
    },
    "clients": {
      "title": "Our Work",
      "subtitle": "See what we've built for businesses like yours"
    }
  }
};
export default messages;